# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.100'
- script: dotnet restore ./DotNetCore2018.WebApi/
  displayName: 'dotnet restore ./DotNetCore2018.WebApi/'
- script: dotnet build --configuration $(buildConfiguration) ./DotNetCore2018.WebApi/
  displayName: 'dotnet build $(buildConfiguration) ./DotNetCore2018.WebApi/'
