# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core SDK 2.2'
  inputs:
    version: '2.2.100'
- script: dotnet restore ./DotNetCore2018.WebApi/
  displayName: 'dotnet restore'
- script: dotnet build --configuration $(buildConfiguration) ./DotNetCore2018.WebApi/
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: AzureRmWebAppDeployment@3
  displayName: 'Publish to Azure App Services'
  inputs:
    azureSubscription: 'azure-app-service-connection'
    WebAppName: 'dotnetcore2018'
    Package: $(System.ArtifactsDirectory)/**/*.zip
