version: '3.4'

services:
    mssql:
        image: mcr.microsoft.com/mssql/server
        container_name: mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Admin1234567890
        expose:
            - "1433"
        healthcheck:
            test: ["CMD", "ping", "-c", "3", "http://localhost:1433"]
            interval: 30s
            timeout: 10s
            retries: 5

    dotnetcore2018.webapi:
        build:
            context: .
            dockerfile: DotNetCore2018.WebApi/Dockerfile
        depends_on:
            - mssql
        links:
            - mssql

    proxy:
        build:
            context:  ./nginx
            dockerfile: Dockerfile
        container_name: proxy
        ports:
            - "5000:80"
        depends_on:
            - dotnetcore2018.webapi
        links:
            - dotnetcore2018.webapi